board/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'board'
urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>', base_views.detail, name='detail'),

    # question_views.py
    path('question/create', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question,
         name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer,
         name='comment_create_answer'),
    # path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer,
    #      name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer,
         name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>', vote_views.vote_answer, name='vote_answer'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .views import CustomLoginView

app_name = "common"

urlpatterns = [
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

handler404 = 'common.views.page_not_found'

board/views/base_views.py
from datetime import datetime, timedelta

from django.core.paginator import Paginator
from django.db.models import Q, Count, F
from django.shortcuts import render, get_object_or_404


from board.forms import AnswerForm
from board.models import Question


import logging
logger = logging.getLogger('board')




def index(request):
    """
    게시판 목록 출력
    """

    # 입력 파라미터
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    # 검색
    if kw:
        question_list = Question.objects.filter(
            Q(subject__icontains=kw) |  # 제목에서 검색
            Q(content__icontains=kw) |  # 내용에서 검색
            Q(author__username__icontains=kw) | #질문 글쓴이에서 검색
            Q(answer__author__username__icontains=kw)   #답변 글쓴이에서 검색
        ).distinct()
    else:
        question_list = Question.objects.all()

    # 정렬
    if so == 'recommend':
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    elif so == 'view':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-hit', '-create_date')
    else:
        question_list = question_list.order_by('-create_date')

    # 페이징 처리
    # page = request.GET.get('page', 1)
    paginator = Paginator(question_list, 10)  # 한 페이지 당 10개씩
    page_obj = paginator.get_page(page)

    last_page = page_obj.paginator.page_range[-1]

    context = {'question_list': page_obj, 'last_page': last_page,
               'kw': kw, 'page': page, 'so': so
               }
    return render(request, 'board/question_list.html', context)


def detail(request, question_id):
    """
    게시판 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "GET":

        answer_form = AnswerForm()
        context = {'question': question, 'answer_form': answer_form}

        q_id: str = str(question.id)

        # 로그인 한 경우
        if request.user.is_authenticated is True:
            cookie_hits_key = f'hits_{request.user.id}'
        # 비로그인 경우
        else:
            cookie_hits_key = 'hits_0'

        # 쿠키로부터 방문기록 로드
        cookie_hits_value: str = request.COOKIES.get(cookie_hits_key, '')

        # 쿠키에 cookie_hits_key 항목이 있는 경우
        if cookie_hits_value != '':
            q_id_list = cookie_hits_value.split('|')
            # 방문한 경우는 그대로 응답
            if q_id in q_id_list:
                return render(request, 'board/question_detail.html', context)
            # 방문하지 않은 경우
            else:
                new_hits_dict = (cookie_hits_key, cookie_hits_value+f'|{q_id}')
                question.hit = F('hit') + 1
                question.save()
                question.refresh_from_db()
        # hits 가 없는 경우
        else:
            new_hits_dict = (cookie_hits_key, q_id)
            question.hit = F('hit') + 1
            question.save()
            question.refresh_from_db()

        response = render(request, 'board/question_detail.html', context)

        # 만료시간 설정
        midnight_kst = datetime.replace(datetime.utcnow() + timedelta(days=1, hours=9), hour=0, minute=0, second=0)
        midnight_kst_to_utc = midnight_kst - timedelta(hours=9)

        response.set_cookie(*new_hits_dict,
                            expires=midnight_kst_to_utc,
                            # secure=True,
                            httponly=True,
                            samesite='Strict')
        return response

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=0.7">
    <meta name="description" content="Django로 만든 간단한 게시판입니다.">
    <meta name="author" content="leeyongjoo">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Font -->
    <link rel="stylesheet" type="text/css"
          href="https://cdn.rawgit.com/innks/NanumSquareRound/master/nanumsquareround.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %} : LYJ BOARD</title>
</head>

<body class="col-lg-8 mx-auto p-3 py-md-5">

{% block header %}
{% include "base_header.html" %}
{% endblock %}

<!-- 각 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 각 템플릿 안에 삽입될 내용 End -->

{% block footer %}
{% include "base_footer.html" %}
{% endblock %}

{% include "base_script.html" %}

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/base_footer.html
<footer class="pt-5 my-5 text-muted border-top text-center user-select-none">
        leeyongjoo &copy; 2021
</footer>

templates/base_header.html
<header class="d-flex justify-content-between align-items-center pb-3 mb-5 border-bottom">
    <a href="/" class="d-flex align-items-center dark text-secondary text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-house-fill"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
            <path fill-rule="evenodd"
                  d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
        </svg>
        <span class="text-secondary fs-3 p-0"></span>
    </a>

    <div class="d-md-flex justify-content-md-end user-select-none">
        {% if user.is_authenticated %}
        <div>
            <span class="align-middle">👋 {{ user.username }}</span>
            <a class="btn btn-light" href="{% url 'common:logout' %}">Logout</a>
        </div>
        {% else %}
        <a href="{% url 'common:login' %}" class="btn btn-link me-md-2" type="button">Sign In</a>
        <a href="{% url 'common:signup' %}" class="btn btn-dark" type="button">Sign Up</a>
        {% endif %}
    </div>
</header>

templates/base_script.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/head.html
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=0.7">
    <meta name="description" content="Django로 만든 간단한 게시판입니다.">
    <meta name="author" content="leeyongjoo">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Font -->
    <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/innks/NanumSquareRound/master/nanumsquareround.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap" rel="stylesheet">

    <title>Untitled.</title>
</head>