board/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'board'
urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>', base_views.detail, name='detail'),

    # question_views.py
    path('question/create', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question,
         name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question,
         name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question,
         name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>', comment_views.comment_create_answer,
         name='comment_create_answer'),
    # path('comment/modify/answer/<int:comment_id>', comment_views.comment_modify_answer,
    #      name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>', comment_views.comment_delete_answer,
         name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>', vote_views.vote_answer, name='vote_answer'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from board.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

handler404 = 'common.views.page_not_found'

board/models.py
from django.contrib.auth.models import User
from django.db import models

# TODO: date 필드 수정
#  auto_add, auto_add_now 추가하기

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    voter = models.ManyToManyField(User, related_name='voter_question')
    hit = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

    question = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, on_delete=models.CASCADE)

board/forms.py
from django import forms
from .models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject': '제목',
            'content': '내용',
        }

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

        labels = {
            'content': '답변 내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from django.utils import timezone

from board.forms import AnswerForm, QuestionForm
from board.models import Answer, Question


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    답변 작성
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            answer = Answer(question=question, **answer_form.cleaned_data)
            answer.create_date = timezone.now()
            answer.author = request.user
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('board:detail', question_id=question.id), answer.id))
    else:
        answer_form = AnswerForm()
    context = {'question': question, 'form': answer_form}
    return render(request, 'board/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    게시판 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('{}#answer_{}'.format(
            resolve_url('board:detail', question_id=answer.question.id), answer.id))

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)

        if form.is_valid():
            modified_answer = form.save(commit=False)
            modified_answer.author = request.user
            modified_answer.modify_date = timezone.now()
            modified_answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('board:detail', question_id=answer.question.id), answer.id))

    else:
        form = QuestionForm(instance=answer)
    context = {'form': form}
    return render(request, 'board/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    게시판 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('{}#answer_{}'.format(
            resolve_url('board:detail', question_id=answer.question.id), answer.id))
    answer.delete()
    return redirect('{}#answer_{}'.format(
        resolve_url('board:detail', question_id=answer.question.id), answer.id))

board/views/base_views.py
from datetime import datetime, timedelta

from django.core.paginator import Paginator
from django.db.models import Q, Count, F
from django.shortcuts import render, get_object_or_404


from board.forms import AnswerForm
from board.models import Question


import logging
logger = logging.getLogger('board')




def index(request):
    """
    게시판 목록 출력
    """

    # 입력 파라미터
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    # 검색
    if kw:
        question_list = Question.objects.filter(
            Q(subject__icontains=kw) |  # 제목에서 검색
            Q(content__icontains=kw) |  # 내용에서 검색
            Q(author__username__icontains=kw) | #질문 글쓴이에서 검색
            Q(answer__author__username__icontains=kw)   #답변 글쓴이에서 검색
        ).distinct()
    else:
        question_list = Question.objects.all()

    # 정렬
    if so == 'recommend':
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    elif so == 'view':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-hit', '-create_date')
    else:
        question_list = question_list.order_by('-create_date')

    # 페이징 처리
    # page = request.GET.get('page', 1)
    paginator = Paginator(question_list, 10)  # 한 페이지 당 10개씩
    page_obj = paginator.get_page(page)

    last_page = page_obj.paginator.page_range[-1]

    context = {'question_list': page_obj, 'last_page': last_page,
               'kw': kw, 'page': page, 'so': so
               }
    return render(request, 'board/question_list.html', context)


def detail(request, question_id):
    """
    게시판 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "GET":

        answer_form = AnswerForm()
        context = {'question': question, 'answer_form': answer_form}

        q_id: str = str(question.id)

        # 로그인 한 경우
        if request.user.is_authenticated is True:
            cookie_hits_key = f'hits_{request.user.id}'
        # 비로그인 경우
        else:
            cookie_hits_key = 'hits_0'

        # 쿠키로부터 방문기록 로드
        cookie_hits_value: str = request.COOKIES.get(cookie_hits_key, '')

        # 쿠키에 cookie_hits_key 항목이 있는 경우
        if cookie_hits_value != '':
            q_id_list = cookie_hits_value.split('|')
            # 방문한 경우는 그대로 응답
            if q_id in q_id_list:
                return render(request, 'board/question_detail.html', context)
            # 방문하지 않은 경우
            else:
                new_hits_dict = (cookie_hits_key, cookie_hits_value+f'|{q_id}')
                question.hit = F('hit') + 1
                question.save()
                question.refresh_from_db()
        # hits 가 없는 경우
        else:
            new_hits_dict = (cookie_hits_key, q_id)
            question.hit = F('hit') + 1
            question.save()
            question.refresh_from_db()

        response = render(request, 'board/question_detail.html', context)

        # 만료시간 설정
        midnight_kst = datetime.replace(datetime.utcnow() + timedelta(days=1, hours=9), hour=0, minute=0, second=0)
        midnight_kst_to_utc = midnight_kst - timedelta(hours=9)

        response.set_cookie(*new_hits_dict,
                            expires=midnight_kst_to_utc,
                            # secure=True,
                            httponly=True,
                            samesite='Strict')
        return response

board/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, resolve_url

from board.forms import CommentForm
from board.models import Comment, Question, Answer


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    게시판 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.question = question
            comment.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'board/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    게시판 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('board:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect('board:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'board/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    게시판 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제 권한이 없습니다')
        return redirect('board:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('board:detail', question_id=comment.question.id)

#########################################################################

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    게시판 답변댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('board:detail', question_id=comment.answer.question.id), answer.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'board/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    게시판 답변댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제 권한이 없습니다')
        return redirect('{}#answer_{}'.format(
            resolve_url('board:detail', question_id=comment.answer.question.id), comment.answer.id))
    else:
        comment.delete()
    return redirect('{}#answer_{}'.format(
        resolve_url('board:detail', question_id=comment.answer.question.id), comment.answer.id))

board/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from board.forms import QuestionForm
from board.models import Question


@login_required(login_url='common:login')
def question_create(request):
    """
    게시판 질문등록
    """
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            # question = form.save(commit=False)
            question = Question(**form.cleaned_data)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('board:index')
    else:
        form = QuestionForm()
    return render(request, 'board/question_form.html', {'form': form})


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    게시판 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('board:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            modified_question = form.save(commit=False)
            modified_question.author = request.user
            modified_question.modify_date = timezone.now()
            modified_question.save()
            return redirect('board:detail', question_id=modified_question.id)

    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'board/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    게시판 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:detail', question_id=question.id)
    question.delete()
    return redirect('board:index')

board/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, resolve_url

from board.models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    게시판 질문추천등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    # 이미 추천한 경우
    elif len(request.user.voter_question.filter(pk=question_id)) > 0:
        question.voter.remove(request.user)
    else:
        question.voter.add(request.user)
    return redirect('board:detail', question_id=question_id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    게시판 답변추천등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    # 이미 추천한 경우
    elif len(request.user.voter_answer.filter(pk=answer_id)) > 0:
        answer.voter.remove(request.user)
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
        resolve_url('board:detail', question_id=answer.question.id), answer.id))

templates/board/answer_form.html
{% extends 'base.html' %}

{% block title %}답변 등록{% endblock %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/comment_form.html
{% extends 'base.html' %}

{% block title %}댓글 등록{% endblock %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/question_detail.html
{% extends 'base.html' %}

{% block title %}{{ question.subject }}{% endblock %}

{% load board_filter %}

{% block content %}

<article class="blog-post">
    <div class="d-grid gap-2">
        <div class="card g-5 rounded shadow-sm">
            <div class="card-body">
                <h2 class="blog-post-title">{{ question.subject }}</h2>
                <h6 class="card-subtitle mb-2 text-muted">{{ question.create_date|date:'Y-m-d H:i' }} by
                    <b>{{ question.author.username }}</b>
                    {% if question.modify_date %}(수정: {{ question.modify_date|date:'Y-m-d H:i' }}){% endif %}</h6>
                <p class="card-text"></p>

                <div class="d-flex justify-content-between">
                    <div>
                        <a href="{% url 'board:vote_question' question.id %}" data-uri="" id="recommend">
                            <button type="button"
                                    class="btn btn-{% if user.is_authenticated %}{% if user in question.voter.all %}primary{% endif %}{% endif %}">
                                <i class="bi bi-hand-thumbs-up-fill"></i>
                                <span class="badge bg-light" style="color:black;">{{ question.voter.count }}</span>
                            </button>
                        </a>
                    </div>
                    <div>
                    <span class="align-middle user-select-none">
                    <i class="bi bi-eye-fill"></i> {{ question.hit }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="card gap-1 rounded shadow-sm">
            <div class="card-body">
                {{ question.content|escape|mark }}
            </div>

            {% if request.user == question.author %}
            <div class="my-3 mx-auto user-select-none">
                <a href="{% url 'board:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:;" class="delete btn btn-sm btn-outline-danger" onclick="clickDeleteButton(this);"
                   data-uri="{% url 'board:question_delete' question.id  %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
</article>

<!-- 사용자오류 표시 -->
<div class="container my-3">

    <div class="modal fade" id="recommendErrorModal" tabindex="-1" aria-labelledby="alertModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" role="alert">
                {% for message in messages %}
                <div class="modal-header alert-warning">
                    <h5 class="modal-title" id="alertModalTitle">Messages</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body alert-warning">

                    <h4 class="alert-heading">{{ message.tags|title }}!</h4>
                    <p>{{ message.message }}</p>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>

<!-- 답변 부분 시작 -->

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field in form %}
    {% if field.errors %}
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
    {% endif %}
    {% endfor %}
</div>
{% endif %}

<div class="card my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0 text-end user-select-none">{{question.answer_set.count}} 개의 답변이 있습니다.</h6>

    <!-- 답변 -->
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}" class="anchor"></a>

    <div class="d-flex text-muted pt-3 row">
        <svg xmlns="http://www.w3.org/2000/svg" role="img" width="32" height="32" fill=""
             class="bi bi-person-square bd-placeholder-img flex-shrink-0 rounded col-auto" viewBox="0 0 16 16"
             aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>
            Placeholder</title>
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z"/>
        </svg>
        <div class="pb-3 mb-0 small border-bottom col w-auto">
            <div class="row justify-content-between">
                <strong class="d-block text-gray-dark col-4">{{ answer.author.username }}</strong>
                <div class="col-4 ps-1 text-end user-select-none">
                    {% if request.user == answer.author %}
                    <a href="{% url 'board:answer_modify' answer.id %}" class="link-secondary">수정</a>
                    <a href="javascript:" class="delete link-danger"
                       data-uri="{% url 'board:answer_delete' answer.id %}" onclick="clickDeleteButton(this);">삭제</a>
                    {% endif %}
                </div>
            </div>

            <div class="fs-5">{{ answer.content }}</div>
            <div class="row user-select-none">
                <div class="text-gray">
                    ({{ answer.create_date|date:'Y-m-d H:i' }}{% if answer.modify_date %} | 수정:
                    {{ answer.modify_date|date:'Y-m-d H:i' }}{% endif %})
                </div>

                {% for comment in answer.comment_set.all %}
                <div>
                    <div class="badge bg-light text-wrap text-start lh-base" style="font-size: 0.8rem;">
                        {{ comment.content }} ( {{ comment.author }} | {{ comment.modify_date|date:"Y-m-d H:i" }} )
                        {% if request.user == comment.author %}
                        <a href="javascript:" style="color:grey;"
                           data-uri="{% url 'board:comment_delete_answer' comment.id %}"
                           onclick="clickDeleteButton(this);">
                            <i class="bi bi-x-square-fill"></i></a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                <small class="d-block text-start mt-3 user-select-none">
                    <form action="{% url 'board:comment_create_answer' answer.id %}" method="post">
                        {% csrf_token %}
                        <a href="javascript:;" onclick="addCommentInput(this);">댓글 추가</a>
                    </form>
                </small>

            </div>
        </div>

    </div>

    {% endfor %}

    <small class="d-block text-end mt-3 user-select-none">
        <a href="#" data-bs-toggle="modal" data-bs-target="#answerAdd">답변 추가</a>
    </small>

    <div class="modal fade" id="answerAdd" tabindex="-1" aria-labelledby="answerAddLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="answerAddLabel">답변 추가</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="content" class="col-form-label">답변 내용:</label>
                        <textarea class="form-control" name="content"
                                  {% if not user.is_authenticated %}disabled{% endif %}
                                  id="content"
                                  rows="5">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                        <button type="submit" class="btn btn-primary">저장</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
</div>
<!-- 답변 부분 끝 -->

{% endblock %}

{% block script %}
<script type='text/javascript'>
function clickDeleteButton(e) {
    if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = e.dataset.uri
    }
}

function addCommentInput(obj) {

    var newdiv = document.createElement('div')
    newdiv.innerHTML = "<input id='inputComment' name='content' type='text' class='form-control' placeholder='댓글을 입력하세요.' onkeypress='javascript:enterComment(this);'>"
    obj.parentElement.appendChild(newdiv)
    obj.remove()
    newdiv.children[0].focus()

}

function enterComment(e) {
    if (!e) e = window.event;
    var keyCode = e.code || e.key;
    if (keyCode == 'Enter'){
        e.parentElement.parentElement.submit()
    }
}

{% if messages %}
var myModal = new bootstrap.Modal(document.getElementById("recommendErrorModal"), {})
document.onreadystatechange = function () {
  myModal.show()
}
{% endif %}

</script>
{% endblock %}

templates/board/question_form.html
{% extends 'base.html' %}

{% block title %}질문 등록{% endblock %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}